version: '3.11'

services:
  telegram_bot:
    container_name: tgm_bot
    build: 
      context: ./tg_bot
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
    volumes:
      - ./tg_bot:/tg_bot
    command: /bin/bash -c "python tg_bot_app.py"
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]